### ISSUE TITLE
how can I get the session token that I need to send in the authorizer.

### ISSUE THREAD

**Issue by pabloviniciusBR** [ericpedra/quotexapi#3]
Hello eric, how can I get the session token that I need to send in the authorizer.

I'm a big fan of your work, I hope one day to learn how to build APIs like you, eric my name is vinicius, if you have any material about the API could you send it to my email?
pablovinicius.pessoal@gmail.com

I would really appreciate it, thank you Eric.

A handshake from Brazil.

**Comment by ericpedra** [comment]
Documentation for WebSocket app
https://websocket-client.readthedocs.io/en/latest/app.html#websocket._app.WebSocketApp
