### ISSUE TITLE
In Brazil we have several probabilistic strategies such as: MHI minority, Impaer pattern, Twin towers I used the IQ Option API and built a machine learning based on +200 strategies, send me your email so I can share my ideas with you.

### ISSUE THREAD

**Issue by pabloviniciusBR** [ericpedra/quotexapi#4]
In Brazil we have several probabilistic strategies such as: MHI minority, Impaer pattern, Twin towers I used the IQ Option API and built a machine learning based on +200 strategies, send me your email so I can share my ideas with you.

**Comment by ericpedra** [comment]
erikpedraz1@gmail.com

**Comment by Cedrick-J** [comment]
cedrick@habertech.info
